
# This file is automatically generated, you probably don't want to edit this

ScoringOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ScoringOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            factors = NULL,
            covs = NULL,
            covsTransformations = list(
                "linear",
                "quadratic",
                "cubic",
                "log",
                "sqrt"),
            scoreTypes = list(
                "equivalent",
                "standardized",
                "percent"),
            method = "univariate", ...) {

            super$initialize(
                package="NeuroStatsj",
                name="Scoring",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                default=NULL,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..covsTransformations <- jmvcore::OptionNMXList$new(
                "covsTransformations",
                covsTransformations,
                options=list(
                    "linear",
                    "quadratic",
                    "cubic",
                    "log",
                    "log10",
                    "sqrt",
                    "reciprocal"),
                default=list(
                    "linear",
                    "quadratic",
                    "cubic",
                    "log",
                    "sqrt"))
            private$..scoreTypes <- jmvcore::OptionNMXList$new(
                "scoreTypes",
                scoreTypes,
                options=list(
                    "equivalent",
                    "standardized",
                    "percent"),
                default=list(
                    "equivalent",
                    "standardized",
                    "percent"))
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "univariate",
                    "best"),
                default="univariate")

            self$.addOption(private$..dep)
            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..covsTransformations)
            self$.addOption(private$..scoreTypes)
            self$.addOption(private$..method)
        }),
    active = list(
        dep = function() private$..dep$value,
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        covsTransformations = function() private$..covsTransformations$value,
        scoreTypes = function() private$..scoreTypes$value,
        method = function() private$..method$value),
    private = list(
        ..dep = NA,
        ..factors = NA,
        ..covs = NA,
        ..covsTransformations = NA,
        ..scoreTypes = NA,
        ..method = NA)
)

ScoringResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ScoringResults",
    inherit = jmvcore::Group,
    active = list(
        univariate = function() private$.items[["univariate"]],
        multiple = function() private$.items[["multiple"]],
        zscores = function() private$.items[["zscores"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Scoring")
            self$add(jmvcore::Table$new(
                options=options,
                name="univariate",
                title="Univariate effects",
                columns=list(
                    list(
                        `name`="term", 
                        `type`="text", 
                        `title`="Predictors"),
                    list(
                        `name`="b", 
                        `type`="number", 
                        `title`="Coef"),
                    list(
                        `name`="r2", 
                        `type`="number", 
                        `title`="R\u00B2"),
                    list(
                        `name`="ftest", 
                        `type`="number", 
                        `title`="F"),
                    list(
                        `name`="df1", 
                        `type`="integer", 
                        `title`="df1"),
                    list(
                        `name`="df2", 
                        `type`="integer", 
                        `title`="df2"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue")),
                clearWith=list(
                    "dep",
                    "factors",
                    "covs")))
            self$add(jmvcore::Table$new(
                options=options,
                name="multiple",
                title="Multiple model",
                columns=list(
                    list(
                        `name`="term", 
                        `type`="text", 
                        `title`="Predictors"),
                    list(
                        `name`="b", 
                        `type`="number", 
                        `title`="Coef"),
                    list(
                        `name`="se", 
                        `type`="number", 
                        `title`="SE"),
                    list(
                        `name`="t", 
                        `type`="number", 
                        `title`="t"),
                    list(
                        `name`="df", 
                        `type`="integer", 
                        `title`="df"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue")),
                clearWith=list(
                    "dep",
                    "factors",
                    "covs")))
            self$add(jmvcore::Output$new(
                options=options,
                name="zscores",
                title="Z-Scores",
                varTitle="`Z_${ dep }`",
                varDescription="Standardized scores",
                clearWith=list(
                    "dep",
                    "factors",
                    "covs")))}))

ScoringBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ScoringBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "NeuroStatsj",
                name = "Scoring",
                version = c(0,0,1),
                options = options,
                results = ScoringResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Scoring
#'
#' 
#' @param data .
#' @param dep Update this when R package is to be dealt with
#' @param factors Update this when R package is to be dealt with
#' @param covs Update this when R package is to be dealt with
#' @param covsTransformations Update this when R package is to be dealt with
#' @param scoreTypes Update this when R package is to be dealt with
#' @param method Update this when R package is to be dealt with
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$univariate} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$multiple} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$zscores} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$univariate$asDF}
#'
#' \code{as.data.frame(results$univariate)}
#'
#' @export
Scoring <- function(
    data,
    dep,
    factors,
    covs = NULL,
    covsTransformations = list(
                "linear",
                "quadratic",
                "cubic",
                "log",
                "sqrt"),
    scoreTypes = list(
                "equivalent",
                "standardized",
                "percent"),
    method = "univariate") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("Scoring requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(covs), covs, NULL))

    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- ScoringOptions$new(
        dep = dep,
        factors = factors,
        covs = covs,
        covsTransformations = covsTransformations,
        scoreTypes = scoreTypes,
        method = method)

    analysis <- ScoringClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

