
# This file is automatically generated, you probably don't want to edit this

scoringOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scoringOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            factors = NULL,
            covs = NULL,
            model_type = "lm",
            covsTransformations = list(
                "lin",
                "log",
                "log100",
                "rec"),
            select = TRUE,
            method = "step",
            direction = "low",
            forced = NULL,
            included = NULL,
            es_zscore = TRUE,
            es_rank = FALSE,
            perc = TRUE,
            perc_type = "eby5",
            score_adjust = TRUE,
            score_raw = FALSE, ...) {

            super$initialize(
                package="NeuroStatsj",
                name="scoring",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                default=NULL,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..factors <- jmvcore::OptionVariables$new(
                "factors",
                factors,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                default=NULL,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))
            private$..model_type <- jmvcore::OptionList$new(
                "model_type",
                model_type,
                default="lm",
                options=list(
                    "lm",
                    "nb",
                    "pois",
                    "beta"))
            private$..covsTransformations <- jmvcore::OptionNMXList$new(
                "covsTransformations",
                covsTransformations,
                options=list(
                    "lin",
                    "log",
                    "log10",
                    "log100",
                    "rec",
                    "sqrt",
                    "quad",
                    "cub"),
                default=list(
                    "lin",
                    "log",
                    "log100",
                    "rec"))
            private$..select <- jmvcore::OptionBool$new(
                "select",
                select,
                default=TRUE)
            private$..method <- jmvcore::OptionList$new(
                "method",
                method,
                options=list(
                    "univariate",
                    "step"),
                default="step")
            private$..direction <- jmvcore::OptionList$new(
                "direction",
                direction,
                default="low",
                options=list(
                    "low",
                    "high"))
            private$..forced <- jmvcore::OptionArray$new(
                "forced",
                forced,
                items="(covs)",
                default=NULL,
                template=jmvcore::OptionGroup$new(
                    "forced",
                    NULL,
                    elements=list(
                        jmvcore::OptionVariable$new(
                            "var",
                            NULL,
                            content="$key"),
                        jmvcore::OptionList$new(
                            "type",
                            NULL,
                            options=list(
                                "auto",
                                "lin",
                                "log",
                                "log10",
                                "log100",
                                "sqrt",
                                "rec",
                                "quad",
                                "cub"),
                            default="auto"))))
            private$..included <- jmvcore::OptionVariables$new(
                "included",
                included,
                default=NULL)
            private$..es_zscore <- jmvcore::OptionBool$new(
                "es_zscore",
                es_zscore,
                default=TRUE)
            private$..es_rank <- jmvcore::OptionBool$new(
                "es_rank",
                es_rank,
                default=FALSE)
            private$..perc <- jmvcore::OptionBool$new(
                "perc",
                perc,
                default=TRUE)
            private$..perc_type <- jmvcore::OptionList$new(
                "perc_type",
                perc_type,
                default="eby5",
                options=list(
                    "eby5",
                    "eby10",
                    "by10",
                    "by5",
                    "all"))
            private$..score_adjust <- jmvcore::OptionBool$new(
                "score_adjust",
                score_adjust,
                default=TRUE)
            private$..score_raw <- jmvcore::OptionBool$new(
                "score_raw",
                score_raw,
                default=FALSE)

            self$.addOption(private$..dep)
            self$.addOption(private$..factors)
            self$.addOption(private$..covs)
            self$.addOption(private$..model_type)
            self$.addOption(private$..covsTransformations)
            self$.addOption(private$..select)
            self$.addOption(private$..method)
            self$.addOption(private$..direction)
            self$.addOption(private$..forced)
            self$.addOption(private$..included)
            self$.addOption(private$..es_zscore)
            self$.addOption(private$..es_rank)
            self$.addOption(private$..perc)
            self$.addOption(private$..perc_type)
            self$.addOption(private$..score_adjust)
            self$.addOption(private$..score_raw)
        }),
    active = list(
        dep = function() private$..dep$value,
        factors = function() private$..factors$value,
        covs = function() private$..covs$value,
        model_type = function() private$..model_type$value,
        covsTransformations = function() private$..covsTransformations$value,
        select = function() private$..select$value,
        method = function() private$..method$value,
        direction = function() private$..direction$value,
        forced = function() private$..forced$value,
        included = function() private$..included$value,
        es_zscore = function() private$..es_zscore$value,
        es_rank = function() private$..es_rank$value,
        perc = function() private$..perc$value,
        perc_type = function() private$..perc_type$value,
        score_adjust = function() private$..score_adjust$value,
        score_raw = function() private$..score_raw$value),
    private = list(
        ..dep = NA,
        ..factors = NA,
        ..covs = NA,
        ..model_type = NA,
        ..covsTransformations = NA,
        ..select = NA,
        ..method = NA,
        ..direction = NA,
        ..forced = NA,
        ..included = NA,
        ..es_zscore = NA,
        ..es_rank = NA,
        ..perc = NA,
        ..perc_type = NA,
        ..score_adjust = NA,
        ..score_raw = NA)
)

scoringResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scoringResults",
    inherit = jmvcore::Group,
    active = list(
        univariate = function() private$.items[["univariate"]],
        multiple = function() private$.items[["multiple"]],
        final = function() private$.items[["final"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Scoring")
            self$add(jmvcore::Table$new(
                options=options,
                name="univariate",
                title="Univariate effects",
                columns=list(
                    list(
                        `name`="term", 
                        `type`="text", 
                        `title`="Predictors"),
                    list(
                        `name`="b", 
                        `type`="number", 
                        `title`="Coef"),
                    list(
                        `name`="r2", 
                        `type`="number", 
                        `title`="R\u00B2"),
                    list(
                        `name`="test", 
                        `type`="number", 
                        `title`="F"),
                    list(
                        `name`="df1", 
                        `type`="integer", 
                        `title`="df1"),
                    list(
                        `name`="df2", 
                        `type`="integer", 
                        `title`="df2"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue")),
                clearWith=list(
                    "dep",
                    "factors",
                    "covs")))
            self$add(jmvcore::Table$new(
                options=options,
                name="multiple",
                title="Multiple model",
                columns=list(
                    list(
                        `name`="term", 
                        `type`="text", 
                        `title`="Predictors"),
                    list(
                        `name`="b", 
                        `type`="number", 
                        `title`="Coef"),
                    list(
                        `name`="se", 
                        `type`="number", 
                        `title`="SE"),
                    list(
                        `name`="test", 
                        `type`="number", 
                        `title`="t"),
                    list(
                        `name`="df", 
                        `type`="integer", 
                        `title`="df"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue")),
                clearWith=list(
                    "dep",
                    "factors",
                    "covs")))
            self$add(jmvcore::Table$new(
                options=options,
                name="final",
                title="Final model",
                columns=list(
                    list(
                        `name`="term", 
                        `type`="text", 
                        `title`="Predictors"),
                    list(
                        `name`="b", 
                        `type`="number", 
                        `title`="Coef"),
                    list(
                        `name`="se", 
                        `type`="number", 
                        `title`="SE"),
                    list(
                        `name`="test", 
                        `type`="number", 
                        `title`="t"),
                    list(
                        `name`="df", 
                        `type`="integer", 
                        `title`="df"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue")),
                clearWith=list(
                    "dep",
                    "factors",
                    "covs")))}))

scoringBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scoringBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "NeuroStatsj",
                name = "scoring",
                version = c(0,0,1),
                options = options,
                results = scoringResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Scoring
#'
#' Something here
#' 
#'
#' @examples
#' \donttest{
#' some code here
#'}
#' @param data the data as a data frame
#' @param dep Update this when R package is to be dealt with
#' @param factors Update this when R package is to be dealt with
#' @param covs Update this when R package is to be dealt with
#' @param model_type .
#' @param covsTransformations Update this when R package is to be dealt with
#' @param select .
#' @param method Update this when R package is to be dealt with
#' @param direction .
#' @param forced a named vector of the form \code{c(var1="type",
#'   var2="type2")}
#' @param included .
#' @param es_zscore .
#' @param es_rank .
#' @param perc .
#' @param perc_type .
#' @param score_adjust .
#' @param score_raw .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$univariate} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$multiple} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$final} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$univariate$asDF}
#'
#' \code{as.data.frame(results$univariate)}
#'
#' @export
scoring <- function(
    data,
    dep = NULL,
    factors,
    covs = NULL,
    model_type = "lm",
    covsTransformations = list(
                "lin",
                "log",
                "log100",
                "rec"),
    select = TRUE,
    method = "step",
    direction = "low",
    forced = NULL,
    included = NULL,
    es_zscore = TRUE,
    es_rank = FALSE,
    perc = TRUE,
    perc_type = "eby5",
    score_adjust = TRUE,
    score_raw = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("scoring requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(factors)) factors <- jmvcore::resolveQuo(jmvcore::enquo(factors))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if ( ! missing(included)) included <- jmvcore::resolveQuo(jmvcore::enquo(included))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(factors), factors, NULL),
            `if`( ! missing(covs), covs, NULL),
            `if`( ! missing(included), included, NULL))

    for (v in factors) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- scoringOptions$new(
        dep = dep,
        factors = factors,
        covs = covs,
        model_type = model_type,
        covsTransformations = covsTransformations,
        select = select,
        method = method,
        direction = direction,
        forced = forced,
        included = included,
        es_zscore = es_zscore,
        es_rank = es_rank,
        perc = perc,
        perc_type = perc_type,
        score_adjust = score_adjust,
        score_raw = score_raw)

    analysis <- scoringClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

